#!/bin/bash

NAME=xdma
PACKAGE_NAME=$NAME-dkms
CVERSION=`dpkg-query -W -f='${Version}' ${PACKAGE_NAME} | awk -F "-" '{print $1}' | cut -d\: -f2`

# Retrieve driver version from package version:
# e.g.: "07.06focal2.01" => "07.06.01"
DVERSION=$(echo ${CVERSION} | sed -E "s/^([[:digit:]]+\.[[:digit:]]+)([[:alpha:]]+[[:digit:]]+)?(\.[[:digit:]]+)$/\1\3/g")

echo "Removing ${NAME} driver (${PACKAGE_NAME} ${DVERSION})"

dkms remove ${NAME}/${DVERSION} --all || true

rmmod xdma-chr
